# frozen_string_literal: true

platform :ios do
  lane :test do
    arn = aws_sns(
      platform: 'APNS',
      platform_name: 'test_app_ios_2',
      platform_apns_private_key_path: 'assets/test_push_cert_2.p12',

      update_if_exists: UI.confirm("Update if exists?")
    )
    puts "test_app_ios ARN: #{arn}"
  end

  lane :test_with_password do
    arn = aws_sns(
      platform: 'APNS',
      platform_name: 'test_app_ios_with_password',
      platform_apns_private_key_path: 'assets/test_push_cert_with_password.p12',
      platform_apns_private_key_password: 'joshissupercool'
    )
    puts "test_app_ios_with_password ARN: #{arn}"
  end
end

platform :android do
  lane :test_gcm do
    arn = aws_sns(
      platform: 'GCM',
      platform_name: 'test_app_android_2'
    )
    puts "test_app_android ARN: #{arn}"
  end

  lane :test_fcm do
    arn = aws_sns(
      platform: 'FCM',
      platform_name: 'test_app_android_2'
    )
    puts "test_app_android ARN: #{arn}"
  end
end
